### ISSUE TITLE
Stats with no values cause error

### ISSUE THREAD

**Issue by ESloman** [ESloman/bsebot#108]
```
Unhandled exception in internal background task 'bseddies_awards'.
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/discord/ext/tasks/__init__.py", line 169, in _loop                                                                               await self.coro(*args, **kwargs)
File "/home/app/discordbot/tasks/monthlyawards.py", line 96, in bseddies_awards
most_bets = self.stats.most_bets_created(*args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/app/discordbot/statsclasses.py", line 648, in most_bets_created
busiest = sorted(bet_users, key=lambda x: bet_users[x], reverse=True)[0]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

If a stat/award has no values then the task will error. We should handle these.

**Comment by ESloman** [comment]
This has been fixed for the majority of cases.
