### ISSUE TITLE
Wordle didn't get solved 10/01/23

### ISSUE THREAD

**Issue by ESloman** [ESloman/bsebot#207]
This is the error message:

```
[WDM] - Downloading: 100%|██████████| 6.96M/6.96M [00:00<00:00, 101MB/s]
Unhandled exception in internal background task 'wordle_message'.
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/discord/ext/tasks/__init__.py", line 169, in _loop
    await self.coro(*args, **kwargs)
File "/home/app/discordbot/tasks/wordletask.py", line 86, in wordle_message
    await wordle_solver.get_driver()
File "/home/app/discordbot/wordle/wordlesolver.py", line 72, in get_driver
    close_button = driver.find_element(By.CLASS_NAME, WORDLE_TUTORIAL_CLOSE_CLASS_NAME)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 861, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".Modal-module_closeIcon__b4z74"} (Session info: headless chrome=108.0.5359.124) 
```

Failed to close the tutorial message. Observing today to see if it was a one off but needs looking at. At the very least needs `try/except` around it to prevent this happening again.

**Comment by ESloman** [comment]
Error happened again today.

**Comment by ESloman** [comment]
The wordle class names have changed - need to find a solution.
